function mexbuild(pathToTbbInclude)
mex('-v','batchop_cpu.cpp', ...
    '-O','-R2018a', ...
    ['-I' pathToTbbInclude],...
    'LDFLAGS=$LDFLAGS -ld_classic',...
    '-ltbb', '-lmwblas', '-lmwlapack');

if gpuDeviceCount > 0
    mexcuda -O -g batchop_gpu.cu -L/usr/local/cuda/lib64 -lcublas -lcusolver;
end
end

